# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - dbexpression-docs

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  GOOGLE_ANALYTICS_ID: G-BND29F2QPK
  SITE_URL: https://dbexpression.com/docs
  BASE_PATH: /docs

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: Create env file
        run: |
          touch .env.local
          echo NEXT_PUBLIC_GOOGLE_ANALYTICS_ID=$GOOGLE_ANALYTICS_ID >> $GITHUB_ENV
          echo SITE_URL=$SITE_URL >> $GITHUB_ENV
          echo BASE_PATH=$BASE_PATH >> $GITHUB_ENV

      - name: npm install, build, and test
        run: |
          npm install
          npm run build

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'dbexpression-docs'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: .
